CREATE TABLE cities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    city_name VARCHAR(100) NOT NULL,
    country VARCHAR(100)
);

INSERT INTO cities (city_name, country) VALUES
('New York', 'United States'),
('Los Angeles', 'United States'),
('Chicago', 'United States'),
('Houston', 'United States'),
('Phoenix', 'United States'),
('London', 'United Kingdom'),
('Manchester', 'United Kingdom'),
('Birmingham', 'United Kingdom'),
('Paris', 'France'),
('Marseille', 'France'),
('Lyon', 'France'),
('Berlin', 'Germany'),
('Munich', 'Germany'),
('Frankfurt', 'Germany'),
('Madrid', 'Spain'),
('Barcelona', 'Spain'),
('Valencia', 'Spain'),
('Rome', 'Italy'),
('Milan', 'Italy'),
('Naples', 'Italy'),
('Lisbon', 'Portugal'),
('Porto', 'Portugal'),
('Brussels', 'Belgium'),
('Amsterdam', 'Netherlands'),
('Rotterdam', 'Netherlands'),
('Copenhagen', 'Denmark'),
('Stockholm', 'Sweden'),
('Oslo', 'Norway'),
('Helsinki', 'Finland'),
('Zurich', 'Switzerland'),
('Vienna', 'Austria'),
('Prague', 'Czech Republic'),
('Budapest', 'Hungary'),
('Warsaw', 'Poland'),
('Krakow', 'Poland'),
('Athens', 'Greece'),
('Istanbul', 'Turkey'),
('Ankara', 'Turkey'),
('Moscow', 'Russia'),
('Saint Petersburg', 'Russia'),
('Beijing', 'China'),
('Shanghai', 'China'),
('Guangzhou', 'China'),
('Tokyo', 'Japan'),
('Osaka', 'Japan'),
('Seoul', 'South Korea'),
('Busan', 'South Korea'),
('Bangkok', 'Thailand'),
('Hanoi', 'Vietnam'),
('Ho Chi Minh City', 'Vietnam'),
('Jakarta', 'Indonesia'),
('Singapore', 'Singapore'),
('Kuala Lumpur', 'Malaysia'),
('Manila', 'Philippines'),
('Sydney', 'Australia'),
('Melbourne', 'Australia'),
('Auckland', 'New Zealand'),
('Toronto', 'Canada'),
('Vancouver', 'Canada'),
('Montreal', 'Canada'),
('Mexico City', 'Mexico'),
('Guadalajara', 'Mexico'),
('Buenos Aires', 'Argentina'),
('Santiago', 'Chile'),
('Lima', 'Peru'),
('Bogotá', 'Colombia'),
('São Paulo', 'Brazil'),
('Rio de Janeiro', 'Brazil'),
('Brasília', 'Brazil'),
('Cape Town', 'South Africa'),
('Johannesburg', 'South Africa'),
('Cairo', 'Egypt'),
('Casablanca', 'Morocco'),
('Nairobi', 'Kenya'),
('Lagos', 'Nigeria'),
('Accra', 'Ghana'),
('Addis Ababa', 'Ethiopia'),
('Dubai', 'United Arab Emirates'),
('Abu Dhabi', 'United Arab Emirates'),
('Doha', 'Qatar'),
('Riyadh', 'Saudi Arabia'),
('Jeddah', 'Saudi Arabia'),
('Kuwait City', 'Kuwait'),
('Tel Aviv', 'Israel'),
('Jerusalem', 'Israel'),
('Tehran', 'Iran'),
('Karachi', 'Pakistan'),
('Lahore', 'Pakistan'),
('Mumbai', 'India'),
('Delhi', 'India'),
('Bangalore', 'India'),
('Chennai', 'India'),
('Kolkata', 'India'),
('Kathmandu', 'Nepal'),
('Dhaka', 'Bangladesh'),
('Yangon', 'Myanmar'),
('Havana', 'Cuba'),
('San Juan', 'Puerto Rico'),
('Panama City', 'Panama'),
('San José', 'Costa Rica');
