CREATE TABLE cities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO cities (name) VALUES
('New York'),
('Los Angeles'),
('Chicago'),
('Houston'),
('Phoenix'),
('Philadelphia'),
('San Antonio'),
('San Diego'),
('Dallas'),
('San Jose'),
('London'),
('Manchester'),
('Birmingham'),
('Paris'),
('Marseille'),
('Lyon'),
('Berlin'),
('Munich'),
('Frankfurt'),
('Madrid'),
('Barcelona'),
('Valencia'),
('Rome'),
('Milan'),
('Naples'),
('Turin'),
('Florence'),
('Venice'),
('Athens'),
('Thessaloniki'),
('Patras'),
('Warsaw'),
('Krakow'),
('Gdansk'),
('Budapest'),
('Debrecen'),
('Szeged'),
('Vienna'),
('Salzburg'),
('Graz'),
('Innsbruck'),
('Zurich'),
('Geneva'),
('Basel'),
('Brussels'),
('Antwerp'),
('Ghent'),
('Lisbon'),
('Porto');

CREATE TABLE IF NOT EXISTS history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cityId INT NOT NULL,
    api VARCHAR(100) NOT NULL,
    temperature FLOAT,
    humidity FLOAT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cityId) REFERENCES cities(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;